### ISSUE TITLE
Configure not to validate empty value

### ISSUE THREAD

**Issue by skfd** [michaelkrog/tel.js#17]
Can I configure tel.js not to validate empty field?

**Comment by michaelkrog** [comment]
Thx for your feedback @skfd.

It seems like a valid case. I will include that in the next release.

**Comment by skfd** [comment]
Awesome! Thank you!

**Comment by michaelkrog** [comment]
Hi.

I must have been sleeping the day I answered this. :)
tel.js should only validate empty field if it has a 'required' attribute.

Check out the demo:
http://michaelkrog.github.io/tel.js/

An empty string is valid there, because the field has no 'required' attribute.
