### ISSUE TITLE
dynamic defaultAreaCode and international

### ISSUE THREAD

**Issue by adrianbardan** [michaelkrog/tel.js#18]
Hi,

This is a great angular plugin!

I think it would be nice to be able to dynamically change the defaultAreaCode and international parameters. 

I've forked your repository and tweaked the directive a bit, so you can do something this: 

<input type="tel" name="phone" default-area-code="{{areaCode}}" international="{{internationalOrNot}}" />

https://github.com/adrianbardan/tel.js/blob/master/src/scripts/directives/input.js

line 28: reset the parameters on each "blur"

line 35: I'm not sure why you wanted to re-format the value only if it is valid, but now we have to re-format it every time, otherwise if the default area changes, it will always be validated with the previous parsers and formatters

line 74: reset parsers and formatters on ngModel

If you like this, maybe you'll want to include it in a next version.

Thanks!

**Comment by michaelkrog** [comment]
Hi @adrianbardan. 

Im glad you like the plugin.
Thank you so much for your feedback. The changes seems great.

Would you mind making PR's for https://github.com/adrianbardan/tel.js/commit/408a8a66a0d68d3631e5f93f535b0a524c1cf326 and https://github.com/adrianbardan/tel.js/commit/c600dff2727f5076251f66d1c8bb13f5bcd82c94?

I'll include it at the next release then.

- Michael

**Comment by michaelkrog** [comment]
Created new issues for this: #19 & #20
