### ISSUE TITLE
alert("blur");

### ISSUE THREAD

**Issue by skfd** [michaelkrog/tel.js#23]
Alert messages are all over code. Is this something not supposed to be released?

**Comment by michaelkrog** [comment]
Woops. Yep, indeed. Should not be there. 
I'll fix it right away.

**Comment by michaelkrog** [comment]
Fixed in https://github.com/michaelkrog/tel.js/commit/4d9109b3ea0cae8a4d17ab4b565638063cb5cecb & https://github.com/michaelkrog/tel.js/commit/274cf3d2dfbb4dc118f11b9ac328cb0aba18eb1f

Released as 1.2.1

**Comment by skfd** [comment]
Huzzah! Thank you for super quick response!
