### ISSUE TITLE
An ngModel of null fails validation

### ISSUE THREAD

**Issue by john-benson** [michaelkrog/tel.js#26]
Similar to previous issues, a null value is causing validation to fail

Is this expected functionality? I have forked the project to achieve the functionality we are looking for but can offer a PR to make the change.

**Comment by michaelkrog** [comment]
No that is not expected behaviour. I guess null should equal an empty string in behaviour. 

Please send PR.

**Comment by john-benson** [comment]
PR #27 addresses this issue.

**Comment by michaelkrog** [comment]
Fixed by #27 and in release 1.2.2.
