### ISSUE TITLE
Bad format display for canadian number

### ISSUE THREAD

**Issue by PiFou86** [michaelkrog/tel.js#28]
Hi,

I ran into issue when trying to format a canadian number. Ex. : 4183334444, it's generating (141) 833-34444 whereas (418) 333-4444.

In the code you search only from the telephonefilter, you use metaDataMain and not the metaData for the format.

Instead it, can you use a think like the following  ?
                        nationalFormats = (metaData[19]?metaData[19]:[]).concat(metaDataMain[19]),
                        internationalFormats = (metaData[20]?metaData[20]:[]).concat(metaDataMain[20]),

Can you add a API to change the display format to a specific one giving the opportunity to set a particular format for a country and for a format like : setFormat("CA", "(\\d{3})(\\d{3})(\\d{4})", "$1 $2-$3") ?

Thx.

**Comment by michaelkrog** [comment]
Hi.

You are right. There is something wrong.
Please, you are welcome to submit a pullrequest with the fixes and a test to prove the fix.

Regarding setting a partilcular format, it shouldn't be neccesary if the formats from libphonenumber are correct. If they are not correct, however, please submit an issue to https://github.com/googlei18n/libphonenumber.
