### ISSUE TITLE
Allow isolated scope

### ISSUE THREAD

**Issue by michaelkrog** [michaelkrog/tel.js#30]
Back in https://github.com/michaelkrog/tel.js/issues/7 we remove isolated scope. But it also causes some issues as it pollutes the outer scope with variables only used by tel.js.

Reimplement isolated scope and consider whether we can allow for a version without isolated scope.

**Comment by michaelkrog** [comment]
Related to https://github.com/michaelkrog/tel.js/issues/29

**Comment by wald-tq** [comment]
What do you think about using a new child scope in the directive:

    scope: true

**Comment by michaelkrog** [comment]
I think it would be the way to go. I have had issues using tel.js together with other frameworks because of the lack of isolation.

The problem that rises with an isolate scope is when other directives are used with the same element and they too have an isolate scope. As I recall, an element can have only ONE isolate scope.

**Comment by michaelkrog** [comment]
Fixed in https://github.com/michaelkrog/tel.js/commit/10ac357bad6ffde8b411c5e94dcf2b45c244957a without resorting to isolated scope as a natural consequence of using Typescript.
