### ISSUE TITLE
Not working with ozLazyloader

### ISSUE THREAD

**Issue by figo2264** [michaelkrog/tel.js#32]
First of all,

Thank you for such a nice module.

it really saved my work.

I think I found one problem.

My application uses ozLazyLoader and somehow your module doesn't work with it.

Hope you can check and find a solution.

Thanks.

**Comment by michaelkrog** [comment]
Hi.

I am glad you like tel.js.
Please create a codepen that reproduces the error.

**Comment by michaelkrog** [comment]
Not reproducible!
