### ISSUE TITLE
Wrong Number when using default-area-code

### ISSUE THREAD

**Issue by wald-tq** [michaelkrog/tel.js#34]
I got a Plunkr: http://plnkr.co/edit/VhoNco?p=preview

Copy following to input: 081539308548 (a valid phonenumber in Germany)

While the input stays in focus the phonenumber in the ng-model is correct and the input is valid.

On blur there is another 49 added: +49 4981 539308548

Expected result on blur would be: +49 8153 9308548

**Comment by michaelkrog** [comment]
I am on this.
Will be releasing a new version soon.
