### ISSUE TITLE
074

### ISSUE THREAD

**Issue by Jemmy** [michaelkrog/tel.js#38]
Please add the code of mobile operator Life 74 for Ukraine UA

**Comment by michaelkrog** [comment]
Hi Jemmy.

You are welcome to make a PR with an updated file from Google libphonenumber.
The file that needs to be updated is https://github.com/michaelkrog/tel.js/blob/master/data/metadatalite.js and can be found in newest release of https://github.com/googlei18n/libphonenumber. The newest release is more up to date and should contain any missing mobile operators.

**Comment by michaelkrog** [comment]
Closing because of no reply.
