### ISSUE TITLE
new series 058 for (UAE) is not supported, it is giving invalid.

### ISSUE THREAD

**Issue by mansi2409** [michaelkrog/tel.js#40]
(+971) 58 ** ** *** new series 058 is not supported, giving invalid error.
https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Arab_Emirates

Let us know once this is resolved.

Thanks

**Comment by michaelkrog** [comment]
Hi @mansi2409.

The metadatalite file is taken directly from Googles project. You should be able to just get the newest version and use that in your project.

https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/metadatalite.js
